version: '3'
services:
  nginx:
    build: ./nginx
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./wwwroot:/usr/local/nginx/html"
      - "./nginx/logs:/usr/local/nginx/logs"
      - "./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf"
      - "./nginx/vhost:/usr/local/nginx/conf/vhost"
    networks:
      - lnmp  
    container_name: nginx  
  php:
    build: ./php
    ports:
      - "9000:9000"
    volumes:
      - "./wwwroot:/usr/local/nginx/html"
      - "./php/php.ini:/usr/local/php/etc/php.ini"
      - "./php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf"
      - "./php/php-fpm.d/:/usr/local/php/etc/php-fpm.d/"
    networks:
      - lnmp  
    container_name: php
  mysql:
    image: mysql:5.7
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "./mysql/my.cnf:/etc/mysql/my.cnf"
      - "./mysql/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - lnmp
    container_name: mysql
networks:
  lnmp:    
